apiVersion: v1
kind: ReplicationController
metadata:
  name: msb-config
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: msb-config
  template:
    metadata:
      name: msb-config
      labels:
        app: msb-config
    spec:
      containers:
      - name: msb-config
        image: @docker.image.prefix@/msb-config
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: msb-config
  namespace: @k8s.namespace@
  labels:
    app: msb-config
spec:
  type: NodePort
  selector:
    app: msb-config
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 31052