apiVersion: v1
kind: ReplicationController
metadata:
  name: msb-api
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: msb-api
  template:
    metadata:
      name: msb-api
      labels:
        app: msb-api
    spec:
      containers:
      - name: msb-api
        image: @docker.image.prefix@/msb-api
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: msb-api
  namespace: @k8s.namespace@
  labels:
    app: msb-api
spec:
  type: NodePort
  selector:
    app: msb-api
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31053

