apiVersion: v1
kind: ReplicationController
metadata:
  name: msb-system
  namespace: @k8s.namespace@
spec:
  replicas: @spec.replicas@
  selector:
    app: msb-system
  template:
    metadata:
      name: msb-system
      labels:
        app: msb-system
    spec:
      containers:
      - name: msb-system
        image: @docker.image.prefix@/msb-system
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: msb-system
  namespace: @k8s.namespace@
  labels:
    app: msb-system
spec:
  type: NodePort
  selector:
    app: msb-system
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31063

